stages:
  - build
  - deploy
variables:
  RUNNER_TAG: "lf-common"
  DEPLOY_RUNNER_TAG: "lf-common"
  IMAGE_NAME: "registry.gitlab.com/mihail999/$CI_PROJECT_NAME:${CI_COMMIT_REF_NAME}_$CI_COMMIT_SHORT_SHA"
  LATEST_IMAGE_NAME: "registry.gitlab.com/mihail999/$CI_PROJECT_NAME:latest"

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        DEPLOY_RUNNER_TAG: "lf-runner-shell1"
        RUNNER_TAG: "lf-runner1"
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        DEPLOY_RUNNER_TAG: "lf-runner-shell1" #now we have only 1 runner-shell        
        RUNNER_TAG: "lf-runner2"


build_images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache --cache-repo $CI_REGISTRY_IMAGE --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME --destination $LATEST_IMAGE_NAME
  tags:
    - $RUNNER_TAG

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $IMAGE_NAME
    - docker stop my_app || true
    - docker rm my_app || true
    - docker run -d -p 5000:5000 --name my_app $IMAGE_NAME
  tags:
    - $DEPLOY_RUNNER_TAG
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - develop
    - main